name: Get Started

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run:  echo what is in this directory?
            ls -a
            echo
            echo Is Java installed?
            Java -version
            echo
            echo Is Git installed?
            git --version
            echo what about build tools?
            gradle --version
